### ISSUE TITLE
Redundant len == 0 check

### ISSUE THREAD

**Issue by e4m2** [orlp/polymur-hash#2]
[This branch](https://github.com/orlp/polymur-hash/blob/master/polymur-hash.h#L235) is never reached since the [same condition](https://github.com/orlp/polymur-hash/blob/master/polymur-hash.h#L287) already exists in the public API.

BTW I found this while implementing PolymurHash in Zig ([here](https://github.com/e4m2/polymurhash-zig) if you're interested). Thanks for your work on this!

**Comment by orlp** [comment]
I am aware. But (blame my Rust background) I'd like each function to be sound on its own, and not invoke undefined behavior when called with zero-length input. And the compiler gets rid of the extra check after inlining.

**Comment by orlp** [comment]
FYI taking a quick look at your repo, my name is Orson, not Orsen.

**Comment by orlp** [comment]
@e4m2 I have already released version 2 of PolymurHash that changed the behavior for zero-length strings because it was brought to my attention that having a static return of 0 is problematic for a variety of probabilistic algorithms like MinHash and HyperLogLog: https://github.com/orlp/polymur-hash/issues/3
